//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Watcher_MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public Nullable<bool> EnabledInAD { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public int GroupsId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
