//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Watcher_MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Computers = new HashSet<Computer>();
        }
    
        public int Id { get; set; }
        public string Owner { get; set; }
        public string Name { get; set; }
        public string BuildingFloor { get; set; }
    
        public virtual ICollection<Computer> Computers { get; set; }
    }
}
